services:
  - type: web
    name: node_heroku
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MESSAGE
        value: Hello, World!
